---
- hosts: all
  become: yes
  user: root
  gather_facts: false
  tasks:
    - name: Install nginx
      apt:
        name: nginx
        state: present
      notify:
        - Restart nginx

    - name: Check nginx status
      service:
        name: nginx
        state: started

  handlers:
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
